dictionaries = [
    "de",
    "en_us",
]
words = [
    "dosb",
    "gotenstra√üe",
    "irlich",
    "lucide",
    "mheob",
    "neuwied",
    "nosonar",
    "pappelstadion",
    "tsg",
    "tsgi",
]
